version: "3.4"

services:
  php:
    build:
      target: app_php-development
    volumes:
      - ./application/:/srv/app
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - database

  nginx:
    volumes:
      - ./application/public:/var/www/public:ro

  mysql:
    image: mysql:8.0.33-debian
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - database

volumes:
  mysql_data:

networks:
  database:
    driver: bridge