CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    tag VARCHAR(30) NOT NULL UNIQUE,
    username VARCHAR(30) NOT NULL,
    createdAt DATETIME DEFAULT NULL,
    updatedAt DATETIME DEFAULT NULL,
    FULLTEXT(tag, username)
) ENGINE=InnoDB;