CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    tag VARCHAR(30) NOT NULL UNIQUE,
    nick VARCHAR(30) NOT NULL
)